### ISSUE TITLE
Blizzard 2008 dataset information

### ISSUE THREAD

**Issue by marzieh-razavi** [idiap/IdiapTTS#1]
Hello, 

Thanks for releasing this repo. The egs/blizzard08_roger/s1/01_setup.sh script seems to be hard-coded for the Blizzard 2008 dataset. Is it possible to provide some information about the structure of the Blizzard 2008 dataset so that the script can be modified to use other datasets?

Thanks.

**Comment by b-schnell** [comment]
Hello Marzieh,

The script moves all audio files into database/wav. If you have multiple speakers use subdirectories with the speaker id. Additionally you need database/utts.data which contains in each line the id of the audio (this can include the speaker subdirectory), a space, and the text spoken in that audio. For LJSpeech it looks like this:
``
LJ002-0036 one. The male debtors' side consisted of a yard forty-nine feet by thirty-one,
LJ002-0037 leading to thirteen wards on various floors, and a day room.
LJ002-0038 Of these wards, three were appropriated to the "cabin side," so called because
LJ002-0039 they each contained four small rooms or "cabins" seven feet square,

``
The script also creates a file_id_list_full.txt and file_id_list_demo.txt which contain a list of ids with just one id per line. The text files basically tell the other scripts which ids to work on.

I did not have time to clean up and upload the settings for LJSpeech yet. I hope to do this in the next weeks. But I am attaching its 01_setup.sh file [here](https://github.com/idiap/IdiapTTS/files/3351025/LJSpeech_01_setup.sh.tar.gz) which works directly on the LJSpeech archive you can [download](https://keithito.com/LJ-Speech-Dataset/).

Let me know if that helps.

**Comment by marzieh-razavi** [comment]
Thanks a lot Bastian for the explanation and uploading the script,  it was really helpful.

**Comment by b-schnell** [comment]
The full LJSpeech setup is now online. So I'm closing this.
